name: Admin CI

on:
  push:
    branches:
      - develop
      - 'milestone/**'
  pull_request:
    branches:
      - develop
      - 'milestone/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./admin
        run: npm install

      - name: Build
        working-directory: ./admin
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: admin-dist
          path: admin/dist

      - name: Deploy placeholder
        if: ${{ secrets.DEPLOY_PROVIDER != '' }}
        run: |
          echo "DEPLOY_PROVIDER is set. Add provider-specific deploy steps here (e.g., Vercel/Heroku)."
